### ISSUE TITLE
Cron job taking a long time

### ISSUE THREAD

**Issue by Syxton** [fernandooliveira/moodle-block_marking_manager#31]
What does the cron task for NED do?  It takes about an hour and a half to run each time.

**Comment by Syxton** [comment]
If we disable the task, what are the consequences?

**Comment by fernandooliveira** [comment]
The con is used to cache activity statuses. For example, it calculates the number of unmarked assignments in a specific course.  It does do this for all courses.  A Cron job is used because instant calculation takes too long, which results in increase page loading time. The Cron job execution time depends on number of course, students and activities. It is also caching group assignments (user specific).

**Comment by Syxton** [comment]
Is there a way to make it only run through the courses that have a NED Block instance?  And only courses that aren't past the closed date(in 3.2)

**Comment by fernandooliveira** [comment]
You can manually select the courses in the block configuration page http://screencast.com/t/jCn1LuT0GLk

**Comment by Syxton** [comment]
Would love a config option for "Only on courses that have the NED block added".  Just need to add

` AND c.id IN (SELECT instanceid FROM {context} WHERE id IN (SELECT parentcontextid FROM {block_instances} WHERE blockname = 'fn_marking'))`

to the sql on line 3197 of lib.php    With that addition, it went from 20k rows of data to less than 100 rows on our dev server, and instead of 2 hours of cron per run it is now just a few seconds.  I believe we are going to run this change in our production server because the long running cron is a blocking issue for us.  Thanks for responding on this.

**Comment by fernandooliveira** [comment]
Thanks for the code. I will look into adding this option to the block config page. Can you tell me how many courses were processed before and after you made this change?

**Comment by Syxton** [comment]
25,706 courses were run through, many of them empty shells (because they are automatically created from our registrar but many are never used), after the code only 4 courses.  I ran this test on our dev server, but if it were running on our production server it would have run 23 courses.

**Comment by fernandooliveira** [comment]
Your site has 25,000 courses!?  Wow.
I will add your code in the near future, but I suspect you could achieve the same result if you just put those 4 courses into a directory and then modify the block config so that it only processes that directory.

**Comment by PickledKitty** [comment]
I would like to second this notion: "Would love a config option for "Only on courses that have the NED block added"", as we are in a similar situation of having thousands of courses and the cron job holding up the rest of the cron process.

Could you please implement as soon as you can so that I can update this plugin and save our cron from going nuts? I'd do it myself in my instance, but we don't like to change code and then have to deal with merge conflicts upon update!

Thanks in advance!

**Comment by fernandooliveira** [comment]
This feature has been implemented. Please download latest release.

**Comment by Syxton** [comment]
@fernandooliveira is this change going to be showing up soon on git?

**Comment by fernandooliveira** [comment]
Git is now updated.  We welcome your feedback regarding how performance can be further improved. Thanks.
